// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelExpenseTracker.Infrastructure.Data;

#nullable disable

namespace TravelExpenseTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("FetchedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("FromCurrency").IsRequired().HasColumnType("text");
                    b.Property<decimal>("Rate").HasPrecision(18, 6).HasColumnType("numeric(18,6)");
                    b.Property<string>("ToCurrency").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("FromCurrency", "ToCurrency");
                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.Expense", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Amount").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<decimal>("AmountInBaseCurrency").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                    b.Property<string>("Category").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Currency").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("Date").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<Guid>("PaidByUserId").HasColumnType("uuid");
                    b.Property<Guid>("VacationId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("PaidByUserId");
                    b.HasIndex("VacationId");
                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasColumnType("text");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                    b.Property<string>("Role").IsRequired().HasColumnType("text");
                    b.Property<string>("Username").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.Vacation", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("BaseCurrency").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("CreatedBy").HasColumnType("uuid");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<DateTime>("EndDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("StartDate").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("CreatedBy");
                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.VacationParticipant", b =>
                {
                    b.Property<Guid>("VacationId").HasColumnType("uuid");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.Property<decimal>("SplitWeight").HasPrecision(10, 6).HasColumnType("numeric(10,6)");
                    b.HasKey("VacationId", "UserId");
                    b.HasIndex("UserId");
                    b.ToTable("VacationParticipants");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.Expense", b =>
                {
                    b.HasOne("TravelExpenseTracker.Core.Models.User", "PaidBy")
                        .WithMany("PaidExpenses")
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("TravelExpenseTracker.Core.Models.Vacation", "Vacation")
                        .WithMany("Expenses")
                        .HasForeignKey("VacationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("PaidBy");
                    b.Navigation("Vacation");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.Vacation", b =>
                {
                    b.HasOne("TravelExpenseTracker.Core.Models.User", "Creator")
                        .WithMany("CreatedVacations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.VacationParticipant", b =>
                {
                    b.HasOne("TravelExpenseTracker.Core.Models.User", "User")
                        .WithMany("VacationParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("TravelExpenseTracker.Core.Models.Vacation", "Vacation")
                        .WithMany("Participants")
                        .HasForeignKey("VacationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                    b.Navigation("Vacation");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.User", b =>
                {
                    b.Navigation("CreatedVacations");
                    b.Navigation("PaidExpenses");
                    b.Navigation("VacationParticipants");
                });

            modelBuilder.Entity("TravelExpenseTracker.Core.Models.Vacation", b =>
                {
                    b.Navigation("Expenses");
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
